### ISSUE TITLE
As a picky eater - how do I find PCs that suit my preferences in a ranked order

### ISSUE THREAD

**Issue by maeandco** [akflds/stpc#2]

**Comment by maeandco** [comment]
Collect and rank "Overall rating" data field

**Comment by akflds** [comment]
@maeandco should we collect all the individual categories (e.g. what if freshness trumps everything for an individual?)

**Comment by maeandco** [comment]
@akflds yes! Categories include:

Price
Size
Batter
Potato core
Consistency
Freshness
Overall rating

**Comment by maeandco** [comment]
Might have to manually collect data for individual categories. Instagram account only has them separated by line breaks

**Comment by akflds** [comment]
never fear - https://www.xkcd.com/208/

**Comment by akflds** [comment]
Ratings extracted from comments and split into the json output. It's over to Tableau for presenting this in a nicer way than the JSON output.
